# Generated by Django 4.2.1 on 2023-06-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_doctor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_location', models.CharField(blank=True, choices=[('Main', '1040 SW 2nd Avenue, Ocala, FL'), ('West', '10230 SW 86th Circle, Ocala, FL')], default='Main', max_length=10, null=True)),
                ('doctor', models.CharField(blank=True, choices=[('Ram Vasudevan, MD, FACC, FACP', 'Ram Vasudevan, MD, FACC, FACP'), ('Punwattie Ramnaraine, FNP-BC', 'Punwattie Ramnaraine, FNP-BC'), ('Alceha Mayne-Thomas, ARNP', 'Alceha Mayne-Thomas, ARNP'), ('Junaina Dominic, PA-C', 'Junaina Dominic, PA-C'), ('Emily Hawkins, APRN, NP-C', 'Emily Hawkins, APRN, NP-C')], max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
